name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  PROD_DOMAIN: ${{ environments.production.vars.PROD_DOMAIN }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Simulate Deploy
        run: echo "Deploying to $PROD_DOMAIN"
