name: Diagnostic Workflow

on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    steps:
      - run: |
          [ -z "${{ vars.APP_ENV }}" ] && echo "::error::APP_ENV missing"
          [ -z "${{ secrets.API_KEY }}" ] && echo "::error::API_KEY missing"
          [ -n "${{ vars.APP_ENV }}" ] && [ -n "${{ secrets.API_KEY }}" ] || exit 1
      - run: |
          echo "## Diagnostic Summary" >> $GITHUB_STEP_SUMMARY
          echo "APP_ENV: ${{ vars.APP_ENV || 'undefined' }}" >> $GITHUB_STEP_SUMMARY
          echo "API_KEY: ${{ secrets.API_KEY && 'defined' || 'undefined' }}" >> $GITHUB_STEP_SUMMARY