name: Environment Variables Demo

on:
  workflow_dispatch:

jobs:
  env-vars-job:
    name: Environment Variables Context
    runs-on: ubuntu-latest
    env:
      APP_ENV: dev-env-override
      LOG_LEVEL: debug

    steps:
      - name: Print environment variables
        env:
          STEP_VAR: step-value
        run: |
          echo "=== Environment Variables ==="
          echo "APP_ENV (env): $APP_ENV"
          echo "SUPPORT_EMAIL (env): $SUPPORT_EMAIL"
          echo "LOG_LEVEL (job env): $LOG_LEVEL"
          echo "STEP_VAR (step env): $STEP_VAR"
          echo "REPO_VAR (vars): ${{ vars.SUPPORT_EMAIL }}"
          echo "SECRET_EXISTS: ${{ secrets.API_KEY != '' }}"

  repo-vars-job:
    name: Repository Variables Context
    runs-on: ubuntu-latest
    needs: env-vars-job

    steps:
      - name: Print repository variables
        run: |
          echo "=== Repository Variables ==="
          echo "APP_ENV (vars): ${{ vars.APP_ENV }}"
          echo "SUPPORT_EMAIL (vars): ${{ vars.SUPPORT_EMAIL }}"

  secrets-job:
    name: Secrets Context
    runs-on: ubuntu-latest
    needs: repo-vars-job

    steps:
      - name: Use secret safely
        run: |
          echo "=== Secrets Handling ==="
          if [ -n "$API_KEY" ]; then
            echo "API_KEY is set (value hidden)"
            # Uso seguro: curl -H "Authorization: Bearer $API_KEY" https://api.example.com
          else
            echo "API_KEY not set"
          fi
        env:
          API_KEY: ${{ secrets.API_KEY }}